version: "3.9"
services:
  # 系統監控代理 - 核心服務
  sys_agent:
    build: .
    container_name: sys-agent
    restart: unless-stopped
    profiles: ["agent", "full"]  # 啟用 agent 或 full profile 時運行

    # 共享主機命名空間，讓 psutil/溫度/NIC I/O 讀到主機資訊
    network_mode: host
    pid: host

    # 只需讀 /sys；/proc 會因 pid: host 自然對應到主機
    volumes:
      - /sys:/sys:ro
      - /dev:/dev:ro   # 非必須，但若未來需要讀一些裝置屬性可用（唯讀即可）

    # 最低權限即可；讀取 /sys /proc 不需要 privileged
    privileged: false
    security_opt:
      - no-new-privileges:true
    read_only: true   # 容器根檔系統唯讀
    tmpfs:
      - /tmp
      - /var/tmp

    environment:
      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT:-1883}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}

  # MQTT Broker - Mosquitto
  mqtt_broker:
    image: eclipse-mosquitto:2.0.21
    container_name: mqtt-broker
    restart: unless-stopped
    profiles: ["broker", "full"]  # 啟用 broker 或 full profile 時運行

    # MQTT 標準端口 + WebSocket
    ports:
      - "1883:1883"        # MQTT TCP
      - "8081:8081"        # MQTT WebSocket (for browser)

    # 配置檔案和密碼檔案
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto_passwd:/mosquitto/config/passwd:ro

    # 安全設定
    security_opt:
      - no-new-privileges:true

  # Web 監控介面 - Nginx 靜態檔案伺服器
  web_monitor:
    image: nginx:alpine    # 輕量級 Nginx (~8MB)
    container_name: monitor-web
    restart: unless-stopped
    profiles: ["web", "full"]  # 啟用 web 或 full profile 時運行

    # 對外提供 Web 介面
    ports:
      - "${WEB_PORT:-8088}:80"  # 主機 port → 容器 port 80

    # 掛載監控頁面
    volumes:
      - ./monitor.html:/usr/share/nginx/html/index.html:ro

    # 安全設定
    security_opt:
      - no-new-privileges:true
    read_only: true        # 容器根檔案系統唯讀
    tmpfs:                 # 臨時檔案使用記憶體
      - /var/cache/nginx
      - /var/run

